### ISSUE TITLE
Job number should be string instead of float

### ISSUE THREAD

**Issue by Hexcles** [w3c/wptdash#22]
In the models, `Job` has a `number` field with type `db.Float`: https://github.com/w3c/wptdash/blob/80e1c395bfc93c3712c91680f8c8ecee7ee90ba6/wptdash/models.py#L206

This causes trailing zeros of the number to be trimmed, among other potential problems. For example, Job 17762.10 becomes 17762.1 (https://pulls.web-platform-tests.org/build/17762).

We should really use `db.String` for this field.

Perhaps existing records in DB also need to be examined/refreshed after this bug is fixed.

**Comment by Hexcles** [comment]
@bobholt

**Comment by bobholt** [comment]
@Hexcles: I'm working on this today. I have the db migration stuff ready, but I'm trying to come up with a safe SQL script to safe convert the correct `*.1`s to `*.10`s

**Comment by bobholt** [comment]
@Hexcles: PR #24 opened for this.

**Comment by bobholt** [comment]
@Hexcles This has been deployed to production, and historical data should have been fixed. See https://pulls.web-platform-tests.org/build/18152 as an example (from 2017-09-04 and now shows 18152.10 as Job Number for Chrome Unstable)

**Comment by Hexcles** [comment]
@bobholt Awesome! Thanks!
