### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by foolip** [w3c/wptdash#23]
If we go ahead with https://github.com/GoogleChrome/wptdashboard/issues/100 then there will be confusion with the similarly named repos.

**Comment by gsnedders** [comment]
wptprdash?

**Comment by marcoscaceres** [comment]
wpt-board? 
wpt-scoreboard?

**Comment by bobholt** [comment]
wpt-pullresults?

**Comment by bobholt** [comment]
This has been renamed to w3c/wpt-pullresults
