### ISSUE TITLE
https://pulls.web-platform-tests.org/build/20897 is 504 Gateway Time-out

### ISSUE THREAD

**Issue by foolip** [w3c/wptdash#42]
Linked from https://github.com/w3c/web-platform-tests/pull/8380

Automatic monitor should be able to notice this when it happens, unknown how long it's been like this.

**Comment by mattl** [comment]
Looks like about 20-25 minutes. I'll take a look now.

**Comment by mattl** [comment]
Back now. I'll continue to keep an eye on it. It was down a little bit over the weekend too and I restarted then as well.

**Comment by foolip** [comment]
What do you think about that monitoring, is there an issue for that?

**Comment by mattl** [comment]
https://github.com/w3c/wpt-pullresults/issues/43
