### ISSUE TITLE
https://pulls.web-platform-tests.org/ is down

### ISSUE THREAD

**Issue by foolip** [w3c/wptdash#46]

**Comment by foolip** [comment]
I just noticed this while tinkering with my StatusCake monitoring that I use mostly for WHATWG. If the site comes back up, then this bug is "why didn't monitoring auto-file an urgent issue".

**Comment by mattl** [comment]
It's back up, though according to my inbox it has been down a few times overnight.

**Comment by foolip** [comment]
What happens when it's down? I assume the results of Travis jobs that finish then just don't go anywhere? On many PRs results are mysteriously missing, but it's not necessarily related.
