### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by foolip** [w3c/wptdash#63]
@jugglinmike, do you want to rename this to match the other repos in https://github.com/web-platform-tests?

Given our vague-but-very-likely-to-happen-eventually plans to unify this and wpt.fyi (into wpt.fyi) I think that "pulls.web-platform-tests.org" might be an OK name, matching the "wpt.fyi" scheme, and I think it's fairly unlikely we'll host the same code at another URL, so not too worried about it becoming wrong.

Other ideas?

**Comment by jugglinmike** [comment]
I think pulls.web-platform-tests.org makes sense, so if you're happy with that, then go for it!

However, I don't follow your logic in this issue's description. I want to make sure I'm giving you feedback based on a full understanding, so I hope you don't mind if I open up the discussion a bit.

The relationship between web-platform-tests.org and wpt.fyi is not clear to me.  I don't understand how it "matches the wpt.fyi scheme".  web-platform-tests.org is authoritative, and (like pull request validation), wpt.fyi seems like a service within it. To me, that suggests renaming wpt.fyi to something like status.web-platform-tests.org (likewise for "results-collection" and "results-analysis").

**Comment by foolip** [comment]
I just mean that these are the actual URLs that these repos are set up at. status.web-platform-tests.org doesn't exist.

**Comment by foolip** [comment]
OK, I'll rename to "pulls.web-platform-tests.org" now. If we set this up elsewhere or change the URL, then we'll just rename again. That seems easier than picking a descriptive name :)
